# 复制本文件为 loginConf.ini 后填写真实值。
# loginConf.ini 已加入 .gitignore，不要提交真实敏感信息。

[upstream_server_login]
# 上游服务端登录参数，用于拉取 TranDetailReport。
api_key = eyJ4NXQjUzI1NiI6Ik9EQm1NVFUwWmpKak9ESmtOR1kxWlRobVlqazJZVFl6TnpSall6SXpNVEJsWWpFME1XSmtZMkl4TmpnM09EZGpZV1E1WldaaE5XSTBOREEzWmpNNE5RPT0iLCJraWQiOiJnYXRld2F5X2NlcnRpZmljYXRlX2FsaWFzIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ==.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IlVubGltaXRlZCIsIm5hbWUiOiJQR1dfUG9ydGFsX0FwcCIsImlkIjozLCJ1dWlkIjoiZWRlYzc0YjQtYzEzMC00YmY3LTlkNTMtNTkwYmU4ZjZhZDBjIn0sImlzcyI6Imh0dHBzOlwvXC9hcGltLXBndy5hcHBzLmlzYm9jcG1zLmphenpjYXNoLmNvbS5wazo0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInBlcm1pdHRlZFJlZmVyZXIiOiIiLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJQR1dfTWVyY2hhbnRfUG9ydGFsIiwiY29udGV4dCI6IlwvcGd3cG9ydGFsXC8xLjAuMCIsInB1Ymxpc2hlciI6ImFkbWluIiwidmVyc2lvbiI6IjEuMC4wIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwidG9rZW5fdHlwZSI6ImFwaUtleSIsInBlcm1pdHRlZElQIjoiIiwiaWF0IjoxNzM5NjEwNzMzLCJqdGkiOiI1NjBhOGM2Ni02Y2UwLTRjZGQtYjUxMi0yN2NlYjZhZGVmZjEifQ==.0XCLVwWOVBpfBcKCGmpoADsjmy_wze8B3NK9rX4pej38lAS95w-AC7kWhzqFpYVBeJ74LRPxZK7KpaBre3vcUaFO3xMcu-aM4UeKSRwE-CP0RqTT4H8Vx-hJetx1LYKHavOXS-Kym5KuCP_sgRiXfxN3w4Ztlz77p2xPxVmsG__kcsdGugoy8DL7KhmrgJAphw_zOyi48ZH9x-aI1AKwVqgVyaUb5mfsRXrpnU-pFDLn1xa_EufavewG9_XpD7iZJq1qIHnXUu5tbnYmZvaMIiUabSEWWRByNqOM6jP75Xm0S-lwmEZfVt_gUmcNKmbgYdCFvJEqv2hbmxEHXpx_yQ==
username =
password =
institution_id =

# 下面这些值如果上游服务端要求就填写；不要求可留空。
ip_address =
session_id =
transition_id =

[upstream_server_session]
# 程序登录上游服务端后会自动写入本段，手动创建时可以不填。
token =
user_id =
user_name =
user_type =
merchant_code =
updated_at =
login_status_code =
schedule_status_code =
scheduled_reports_status_code =
scheduled_reports_count =
download_status_code =
last_report_date =
last_start_date =
last_end_date =
last_report_file_path =
last_report_file_name =
last_report_created_at =
last_downloaded_file =

[tp_backend_login]
# TP 后台登录参数，后续用于拉取收款订单。
base_url =
api_key =
username =
password =

# 下面这些值如果 TP 后台要求就填写；不要求可留空。
ip_address =
session_id =
transition_id =
institution_id =

[tp_backend_session]
# 程序登录 TP 后台后会自动写入本段，手动创建时可以不填。
token =
user_id =
user_name =
user_type =
merchant_code =
updated_at =
login_status_code =
